### ISSUE TITLE
(3주차) 전략 패턴

### ISSUE THREAD

**Issue by KOO-YS** [team-tancheon/book-lounge#10]
@ririkat 님

**전략 패턴**에 대한 간단한 **정의**와
전략 패턴이 속한 범위인 **행위 패턴**은 어떤 특징을 가지고 있는지 설명해주세요.
또한 이번 챕터 상에서 `JdbcContext`를 인터페이스를 사용해 구현하지 않았지만, DI 구조로 만들어야했던 이유를 설명해주세요.

**Comment by ririkat** [comment]
@KOO-YS 님
크게 두 파트로 나눠 답변 드리겠습니다.

<br>

## ✏️ `전략 패턴` 과 `행위 패턴`

<br>

디자인 패턴은 목적에 따라 생성, 구조, 행위 패턴으로 분류할 수 있습니다.

이 중, 전략 패턴은 행위 패턴에 해당하는 디자인패턴 입니다.

<br>

### 행위 패턴

객체나 클래스 간의 교류 방법(행위)을 정의하는 패턴입니다.

객체들간에 알고리즘이나 역할을 어떻게 분담하는지, 즉 객체와 객체의 상호 작용에 의해서 수행을 하게 되는 상황에서 상호간의 결합도(coupling)를 낮추고, 독립성 및 재사용성 등을 확보할 수 있을지에 대해 중점을 둔 디자인 패턴입니다.

(행위 패턴의 종류는 글 하단에 간단히 적어두었습니다.)

<br>

### 전략 패턴

전략 패턴이란, 실행 중에 알고리즘(전략)을 선택할 수 있게 하는 행위 디자인 패턴인데요.

쉽게 말해서, 특정 기능을 수행하는 데에  있어 다양한 알고리즘(전략)이 적용될 수 있는 경우 그 각각의 알고리즘들을 캡슐화하고, 인터페이스를 통해 알고리즘(전략)들을 상호교체가 가능하게 하는 방식을 말합니다.

<br>

<br>

## ✏️ `JdbcContext`를 인터페이스 사용 없이 DI 구조로 만들어야 하는 이유

이번 챕터 상에서 `JdbcContext`를 분리하면서 사용했던 DI 방법이 UserDao와 JdbcContext 사이에 인터페이스를 사용하지 않고 DI를 사용한 부분이 있습니다. (xml을 이용해 빈으로 등록해줌)

DI(의존 관계)의 개념을 충실히 따르면, 클래스 레벨에서 구체적인 의존관계가 만들어지지 않도록 인터페이스를 사용하는 것이 일반적입니다.

하지만. 스프링의 DI를 넓게 보면 IoC의 개념을 포괄하는 개념이기 때문에

- IoC : 객체에 대한 제어권한을 외부에 위임하는 개념

`JdbcContext`를 인터페이스 없이 스프링을 이용해 UserDao 객체에서 사용하게 주입한 것도 DI의 기본을 따르고 있는 방식이라고 볼 수 있습니다. 

<br>

결론적으로,   `JdbcContext`를 DI 구조로 만들었다는 말이죠.

인터페이스의 구현 여부는 잠시 미뤄두고 먼저, `JdbcContext`를 UserDao의 DI 구조로 만들어야 할 이유(빈으로등록할 이유)에 대해서 생각해 보도록 합시다.

해당 챕터에서 `JdbcContext`는 아래의 2가지 특징을 지니고 있기 때문에 DI 구조로 만들어져 사용되었다고 볼 수 있습니다.

1)  공유자원으로 활용하면 좋은 특성을 가지고 있다.

- jdbcContext은 싱글톤의 요건을 갖추고 있고, 서비스 오브젝트로서의 의미가 있기 때문에 공유객체로 사용는 것이 이상적입니다.

2)  jdbcContext가 DI를 통해 다른 빈에 의존하고 있기 때문  (UaserDao와  jdbcContext의 의존관계가 명확)

- DI를 위해서는 주입되는/하는 두 오브젝트 모두 빈으로 등록 되어야 하죠. JdbcContext는 UserDao에서 사용되고 있어 이에 해당한다고 볼 수 있고, 다른 빈의 DI를 받기 위해서라도 스프링 빈으로 등록되어야 합니다.

<br>

그렇다면, 왜 인터페이스를 사용하지 않았을까요?

사실 jdbcContect에 인터페이스를 두고 UserDao가 인터페이스를 사용하도록 만들어도 문제 될 것은 없습니다.

하지만, 인터페이스를 사용하지 않은 이유는 UserDao와 JdbcContext 사이의 긴밀한 관계 때문입니다. 

이 둘을 강한 결합력을 가지고 대체해서 사용할 이유가 없는 관계이기 때문에 굳이 결합도를 떨어뜨려가며 인터페이스를 구현하기보다 강력한 결합을 가진 관계를 허용하면서 스프링 빈으로 등록해 DI되도록 만들어도 좋은 관계이기 때문입니다.

<br>

이와 같이 인터페이스를 사용하지 않고 DI를 적용하는 방식은 관계성을 고려해 필요에 따라 사용할 수도 있는 방법입니다. 때문에 무분별하게 사용되는 것이 아니라 상황에 대한 고려가 필요한 방식입니다.

<br>

@KOO-YS  님, 나름대로 정리를 해 보았는데 답변이 충분히 되었는지 모르겠습니다.

답변에서 오류를 발견하셨거나 의견이 있으시면 코멘트 부탁드립니다.
<br>
