### ISSUE TITLE
(4주차) 예외 전환의 목적

### ISSUE THREAD

**Issue by ksw6169** [team-tancheon/book-lounge#11]
@ririkat 님 안녕하세요.

예외 처리를 하는 방법 중 **예외 전환을 하는 목적**에 대해서 설명해주세요.
새해 복 많이 받으세요. :D

**Comment by ririkat** [comment]
@ksw6169 님 안녕하세요.
답변 드리겠습니다.

<br/>

## 예외 전환을 하는 목적

예외 처리 방법 3가지 (복구, 회피, 전화) 중 
예외 전환은 
 
> 예외를 적절한 예외로 전환해서 밖으로 던지는 것

인데요.

<br/>

이러한 예외 전환의 목적은 보통 두 가지로 사용됩니다.

<br/>

### 예외 전환의 목적

- #### 내부 발생 예외를 그대로 던졌을 때 예외의 의미가 불분명한 경우
  > - 예외에 메소드 특성을 담은 이름을 붙여주는 식으로 사용 (불분명 -> 분명)
  > - 중첩 예외로 전환하는 것이 좋다.
   ```java
   ...
   catch (SQLException e) {
       // 1. 특정 에러 상황의 경우를 구분
       if ( e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY) {
           // 2. 그 상황에 맞는 구체적인 예외명을 붙여 던져줌.
           throw DuplicateUserIdException(e);
       }
       else {
           throw e;
       }
   }
  ```

  책 내용에 있는 예시를 인용하여 설명 드리면
  주석에 설명되어 있는 것과 같이 SQLException 이라는 큰 예외 상황 안에서
  특정 상황에 대해 구체적인 명칭을 부여해 그 의미를 명확하게 전환해 주는 목적이라고 볼 수 있습니다.

- #### 예외 처리를 단순하고 쉽게 만들기 위해 포장하는 경우
  > - 주로 체크 예외를 언체크 예외로 전환하는 데 쓰인다.
  > - 비즈니스적인 의미가 없거나 복구 가능한 예외가 아닐 때 사용

  이 경우는 주로 catch하여 발생할 수 있는 예외 상황들이 비즈니스 로직 상에서 의미 있거나 복구 가능한 예외가 아닐 떄
  언체크(런타임) 예외로 포장해서 던지는 경우입니다.
  런타임 예외는 catch 문으로 잡거나 throws로 선언하지 않아도 되기 때문에 다른 계층의 메소드를 작성할 떄 뷸팔요한 예외처리 선언이 들어가지 않도록 해주어
  굳이 체크 예외로 무의미하게 넘기는 것을 방지하기 위한 목적이라고 볼 수 있습니다.

<br/>

새해 복 많이 받으세요.
감사합니다 : )

**Comment by ksw6169** [comment]
답변주셔서 감사합니다.
