### ISSUE TITLE
(4주차) 예외 처리 방법

### ISSUE THREAD

**Issue by ririkat** [team-tancheon/book-lounge#12]
@KOO-YS 님
이번 주차 내용 중 예외처리 방법 3가지에 대해
간략한 설명과 어떤 상황에서 쓰이는지 설명해주세요.
감사합니다.

**Comment by KOO-YS** [comment]
안녕하세요 @ririkat님
 질문에 대한 답변 드리겠습니다 :)

#### 예외 처리 방법

1. ##### 예외 복구

  - 예외 상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓는 것
  ```
    [ 상황 예시 ]
    파일을 읽을 때 입출력 예외가 발생한다면, 사용자에게 안내 후 다른 파일을 이용하도록 권유하는 방법이 있다. 
  ```
2. ##### 예외 처리 회피

  - 예외를 자신이 담당하지 않고 자신을 호출한 쪽으로 던져버리는 방법
  - `throws`문으로 선언해서 예외가 발생하면 호출 쪽으로 던져지게 함
  - `catch`문으로 일단 예외를 잡은 후에 로그를 남기고 다시 예외 던지는 것(rethrow)
  - 회피의 의도가 분명해야 한다
  ```
    [ 상황 예시 ]
    콜백/템플릿처럼 긴밀한 관계에 있는 다른 오브젝트에게 예외처리를 분명히 지게 하거나, 
    자신을 사용하는 쪽에서 예외를 다루는 게 최선의 방법이라고 확신할 경우 예외처리 회피  
  ```
3. ##### 예외 전환 (exception translation)

  - 예외를 복구해서 정상적인 상태로는 만들 수 없기 때문에 예외를 메소드 밖으로 던짐
  - 예외를 그대로 넘기는 게 아닌 **적절한 예외로 전환해서 던진다**
  ```
    [ 상황 예시 ]
    1. 발생한 예외를 그대로 던지는 것이 적절한 의미 부여가 어려울 경우, 의미를 분명하게 해줄 수 있는 예외로 전환하여 던짐
    2. 의미 있는 & 복구 가능한 예외가 아닐 때, 런타임 에러로 포장해서 던짐
  ```

예외 처리 방법 3가지에 대한 간단 설명과 쓰이는 상황 예시를 들어보았습니다 
추가로 질문이 있다면 코멘트 부탁드립니다 좋은 하루되세요 🧸

**Comment by ririkat** [comment]
확인 했습니다. close 하겠습니다.
