### ISSUE TITLE
(4주차) 스프링의 예외 처리 개선

### ISSUE THREAD

**Issue by KOO-YS** [team-tancheon/book-lounge#13]
다양한 예외를 잡아 처리하는 과정은 더 안정적인 프로그램을 만듭니다.
하지만 여러 예외 처리를 반복하다 보면 코드가 복잡해지고 비즈니스 로직에 집중하기 힘든 경우도 생깁니다.
이런 단점을 개선하기 위해 스프링은 `@ExceptionHandler`와 `@ControllerAdvice`를 지원하는데요, @ksw6169님 두 어노테이션에 대한 사용 방법과 주의할 점을 설명해 주세요

**Comment by ksw6169** [comment]
@KOO-YS 님 답변드립니다.

## `@ExceptionHandler`
- `@Controller`, `@RestController`, `@ControllerAdvice`, `@RestControllerAdvice` 클래스에서 발생한 예외를 별도의 메소드에서 처리할 수 있도록 해주는 어노테이션입니다.
- `@Controller`, `@RestController`, `@ControllerAdvice`, `@RestControllerAdvice`을 사용한 클래스 내에서 예외를 처리할 메서드에 `@ExceptionHandler` 어노테이션을 써주고, 어노테이션의 인자로 어떤 예외를 처리할지 지정해주면 됩니다.
```java
@Controller
public class TestController {

    // 컨트롤러 클래스에서 발생한 RuntimeException 처리
    @ExceptionHandler(RuntimeException.class)
    public ResponseEntity<String> handle(RuntimeException e) {
        return new ResponseEntity<String>(e.getMessage(), HttpStatus.BAD_REQUEST);
    }
}
```

- 아래와 같이 2개 이상의 예외도 처리 가능합니다.
```java
@ExceptionHandler({NullPointerException.class, IllegalArgumentException.class})
public ResponseEntity<String> handle(Exception e) {
    return new ResponseEntity<String>(e.getMessage(), HttpStatus.BAD_REQUEST);
}
```

- 컨트롤러 클래스에서 발생한 예외와 일치하는 `@ExceptionHandler` 메소드가 여러 개 있을 때는 발생한 예외와 정확히 일치하는 메소드가 수행됩니다.
```java
@Controller
public class TestController {

    @GetMapping(value = "/test")
    public void test() {
        throw new NullPointerException();
    }
   
    // 여기서 처리됨
    @ExceptionHandler(NullPointerException.class)
    public ResponseEntity<String> handleNullPointerException(Exception e) {
        return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
    }

    @ExceptionHandler(RuntimeException.class)
    public ResponseEntity<String> handleRuntimeException(Exception e) {
        return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
    }
}
```

- 주의할 점은 컨트롤러 클래스에서 발생한 예외가 `@ExceptionHandler` 메소드에서 지정한 예외 중에 없을 경우 상위의 예외를 처리하는 메소드에서 처리됩니다. (예를 들어, NPE가 발생했는데 NPE를 처리하는 메소드가 없고, RuntimeException을 처리하는 메소드만 있을 경우 RuntimeException을 처리하는 메소드에서 NPE가 처리됩니다. NPE는 RuntimeException을 상속한 클래스이기 때문입니다.)

```java
@Controller
public class TestController {

    @GetMapping(value = "/test")
    public void test() {
        throw new NullPointerException();
    }

    // 여기서 처리됨
    @ExceptionHandler(RuntimeException.class)
    public ResponseEntity<String> handleRuntimeException(Exception e) {
        return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
    }
}
```

<br>

## `@ControllerAdvice`
- `@Controller`, `@RestController` 클래스에서 발생한 예외를 잡아 처리할 수 있게 해주는 어노테이션입니다.
- 즉, 전역적으로 컨트롤러 클래스에서 발생한 예외를 별도의 클래스에서 처리하고자 할 때 사용할 수 있습니다.

```java
@ControllerAdvice
public class GlobalExceptionHandler {

    @ExceptionHandler(NullPointerException.class)
    public ResponseEntity<String> handleNullPointerException(NullPointerException e) {
        return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
    }

    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<String> handleIllegalArgumentException(IllegalArgumentException e) {
        return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
    }
}
```

- 예외를 잡을 범위를 특정 package 범위로 제한할 수도 있습니다.
```java
@ControllerAdvice(basePackages = "com.corgi.example.test")
```

<br>

## 추가
- `@RestControllerAdvice`도 `@ControllerAdvice`와 동일한 기능을 수행하나, `@ControllerAdvice` 에 `@ResponseBody`가 추가된 형태라는 것만 차이가 있습니다.

<br>

## 참고 자료
- [Spring framework reference](https://docs.spring.io/spring-framework/docs/5.3.2/reference/html/web.html#mvc-ann-exceptionhandler)
- [@ControllerAdvice, @ExceptionHandler를 이용한 예외처리 분리, 통합하기](https://jeong-pro.tistory.com/195)

<br>

읽어보시고 궁금하신 사항은 코멘트로 남겨주시면 답변 드리겠습니다~

**Comment by KOO-YS** [comment]
확인했습니다 감사합니다
