### ISSUE TITLE
(6주차) 테스트 대역

### ISSUE THREAD

**Issue by ririkat** [team-tancheon/book-lounge#14]
@ksw6169 님
테스트 대역의 정의와 용도
책에 나온 대표적인 종류 두가지에 대해 설명해주세요.

감사합니다.

**Comment by ksw6169** [comment]
@ririkat 님 
답변드립니다. 이해가 되지 않거나 잘못된 부분은 코멘트로 남겨주세요.

<br>

## 테스트 대역의 정의
- 테스트 대역(Test double)이란 테스트 대상이 사용하는 의존 오브젝트를 대체할 수 있도록 만든 오브젝트를 말합니다.
- 즉, 테스트 대상이 실제 의존하고 있는 환경이나 객체의 역할을 '대신해서 수행할 수 있도록(대역)' 만든 오브젝트입니다.  

<br>

## 테스트 대역의 용도
- 테스트 코드를 작성하다보면 테스트 대상이 의존하고 있는 환경이나 객체의 영향을 받아 테스트가 실패로 끝나는 경우가 더러 있습니다. 이 경우 어디에서 테스트가 실패했는지 원인을 찾기가 어렵고, 실제 테스트하고자 하는 대상에 집중하지 못하는 테스트가 되기 십상이기 때문에 이러한 단점을 해결하고자 테스트 대역을 사용합니다.
- 테스트 대역을 사용하면 테스트 대상이 사용하는 의존 객체를 테스트 대역으로 대체함으로써 테스트 대상이 다른 환경에 독립적으로 실행되도록 만들 수 있고, 테스트 과정에서 실제 의존 객체를 사용하는 것이 아니기 때문에 테스트 수행 속도 또한 향상시킬 수 있습니다. 

<br>

## 테스트 스텁(Test stub)
- 테스트 대역의 하나로, 테스트에서 호출된 요청에 대해 미리 준비해둔 결과를 제공하는 객체입니다. 
- 테스트 시에 프로그래밍 된 것 이외에는 응답하지 않습니다. 

<br>

## 목 오브젝트(Mock object)
- 테스트 대역의 하나로, 행위를 검증하기 위해 사용하는 객체입니다. 
- 테스트 오브젝트와 테스트 대상 사이에서 일어나는 커뮤니케이션 내용을 저장해뒀다가 테스트 결과를 검증하는데 활용할 수 있습니다.
- 주로 반환값이 없는(void) 메소드를 검증할 때 사용합니다.
- 수동으로 만들 수도 있고, 프레임워크(ex. mockito)를 통해 만들 수도 있습니다. 

<br>

## 참고 자료
- [단위 테스트 케이스와 테스트 더블(Test Double)](https://medium.com/@SlackBeck/단위-테스트-케이스와-테스트-더블-test-double-2b88cccd6a96)
- [Test Double(테스트 더블) 알아보기](https://beomseok95.tistory.com/295)
- [Dummy와 Stub](https://m.blog.naver.com/PostView.nhn?blogId=palfuni&logNo=120154483985&proxyReferer=https:%2F%2Fwww.google.co.kr%2F)
- [Test Doubles 정리](https://brunch.co.kr/@tilltue/55)
- [Mock](http://www.incodom.kr/Mock)

**Comment by ririkat** [comment]
확인이 늦었습니다 죄송합니다 ㅠㅠ
