### ISSUE TITLE
(6주차) Mockito

### ISSUE THREAD

**Issue by KOO-YS** [team-tancheon/book-lounge#15]
@ririkat님 
<br>

`Mockito`의 **정의**와,
 **메소드를 활용한 예시**(5개)를 활용하여  `Mockito`의 사용방법을 설명해주세요

**Comment by ririkat** [comment]
@KOO-YS 님
답변 드리겠습니다.

### mockito

mockito란, Mock을 이용한 단위 테스트를 위한 Java mocking framework로 JUnit 위에서 동작합니다.


### 📝 mockito 사용법

mockito를 사용하기 위해서는 우선  `JUnti` 과 `mockito` 의 maven을 추가해줘야 합니다.


- mockito 추가
```xml
<dependency>
    <groupId>org.mockito</groupId>
    <artifactId>mockito-all</artifactId>
    <version>1.10.19</version>
</dependency>
```

- JUnit 추가
```xml
<dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>4.12</version>
</dependency>
```

****

자세한 사용법은 아래 `mockito` 의 메소드들의 예제를 통해 설명하도록 하겠습니다.
- mock() (@Mock, @InjectMocks)
- when()
- doThrow()
- doNothing()
- verify()
- spy() (@Spy)

#### mock()

> 목 객체를 만들어서 반환해주는 메소드
>  mock(클래스) 형식으로 사용


```java
@Test
public void example(){
    User user = mock(User.class);
    assertTrue( user != null );
}
```

<br/>

위의 예제처럼 클래스명을 넘겨서 사용하면 그에 맞는 mock 객체를 반환해주는 역할을 합니다.
mock()을 이용하여 직접 목 오브젝트를 구현해주지 않아도 손쉽게 클래스나 인터페이스의 mock을 만들 수 있는 메소드입니다.

<br/>

mock() 메소드 외에도 `@Mock` 이라는 어노테이션을 사용해서 목 객체를 만드는 방법도 있습니다.
또한, 단순 클래스가 아니라 클래스 내부에 다른 클래스를 포함한 경우에는 `@InjectMock` 이라는 어노테이션을 통해 @Mock이나 @Spy가 분은 목 객체를 @InjectMock 어노테이션이 붙은 객체의 멤버 클래스와 일치하면 주입시켜 사용할 수 있도록 해주는 역할을 합니다.

#### when()
> 특정 목 객체를 만들었다면 이 객체로부터 특정 조건을 지정할 수 있습니다. 이 때 사용하는 것이`when()` 메소드입니다. 
> when(지정메소드).thenReutn(반환값); 형식으로 특정 메소드에 대한 반환값을 설정하는 형식으로 사용할 수 있습니다.

<br/>

- 예시

```java
@Test
public void example(){
    User user = mock(User .class);
    when(user .getName()).thenReturn("Brryu");
    when(user .getAge()).thenReturn(28);
    doNothing().when(p).setAge(anyInt());
    assertTrue("Brryu".equals(user .getName()));
    assertTrue(28== user .getAge());
}
```
이런 식으로 사용할 수 있습니다.
`donothing()`은 void로 선언된 메소드에 when()을 걸고 싶을 때 앞에 붙여주면 됩니다.


#### verify()
> 해당 구문이 호출 되었는지를 체크합니다.

```java
@Test
public void example(){
    User u = mock(User .class);
    doNothing().when(u).setAge(anyInt());
    u.setAge(20);
    // 호출했는지 체크
    verify(u).setAge(anyInt()); //success
    // 최소 한번 이상 호출했는지 체크
    verify(u, atLeastOnce()).setAge(anyInt()); //success
    // n번 이상 호출 했는지 체크  n = 횟수
    verify(u, atMost(n)).setAge(anyInt()); //success
    // 지정된 시간(millis) 안으로 메소드를 호출 했는지 체크
    verify(u, timeout(100)).setName(any(String.class)); // fail
    // never()를 추가하면 호출 안했는지를 체크함
    verify(u, never()).setAge(anyInt()); //fail
}
```


<br/>

when()이나 verify()를 통해 특정 메소드나 조건에 대한 체크를 했다면, 예외도 던질 수 있어야 겠죠. 이런 예외는 `doThrow()` 를 통해 사용할 수 있습니다.

<br/>

#### doThrow()
> 예외를 던져주는 메소드 주로 when()과 함께 쓰인다.

```java
@Test(expected = IllegalArgumentException.class)
public void example(){
    User user= mock(User.class);
    doThrow(new IllegalArgumentException()).when(user).setName(eq("Brryu"));
    String name = "Brryu";
    user.setName(name); //
}
```

<br/>

#### spy()
> 가상의 mock 인스턴스를 만들어서 사용하는 mock()과는 달리 실제 인스턴스를 사용해서 mocking하는 메소드, mockito의 메소드로 행위를 지정해주지 않으면 , 객체를 만들 때 사용한 실제 인스턴스의 메소드를 호출함.
> 반드시 실제 인스턴스가 필요하기 때문에 초기화나, 인덱스가 없는 경우 에러가 발생할 수 있지만 doReturn을 사용해서 문제를 회피할 수 있습니다.

<br/>

```java

List list = new LinkedList();
List spy = spy(list);

when(spy.size()).thenReturn(100); // stubbing

spy.add("one");
spy.add("two");

System.out.println(spy.get(0)); // one
System.out.println(spy.size()); // 100

verify(spy).add("one");
verify(spy).add("two");

// Wrong use case
when(spy.get(10)).thenReturn("foo"); // IndexOutOfBoundsException

// use doReturn() instead
doReturn("foo").when(spy).get(0);
```

****

<br/>
이해가 되지 않는 부분은 코멘트 부탁드립니다.

감사합니다.

<br/>

[참고 링크1](https://jdm.kr/blog/222)
[참고 링크2](https://bestalign.github.io/2016/07/10/intro-mockito-2/)

**Comment by KOO-YS** [comment]
감사합니다. 퍼가요~♡
