### ISSUE TITLE
(6주차) 테스트 스텁과 목 오브젝트의 차이점

### ISSUE THREAD

**Issue by ksw6169** [team-tancheon/book-lounge#16]
@KOO-YS 님

테스트 대역(Test double) 중 하나인 테스트 스텁(Test stub)과 목 오브젝트(Mock object)의 차이점에 대해 설명해주세요.

**Comment by KOO-YS** [comment]
안녕하세요 @ksw6169 님
<br>

테스트 스텁과 목 오브젝트에 대해 설명하기 전, 

두 가지를 포함한 범위인 테스트 대역을 먼저 설명해드리겠습니다 :)
<br>

### 테스트 대역(Test Double)이란?

<img src="http://xunitpatterns.com/Types%20Of%20Test%20Doubles.gif">

테스트 하려는 객체가 다른 객체들과 여러 관계가 엮여있어 사용하기 어려울 때, **대체할 수 있는 객체**를 말합니다.

테스트 대역은 Dummy, Stub, Spy, Mock, Fake로 나눌 수 있으며

그 중에서 Stub, Mock에 대해 상세 설명을 더하겠습니다.

- ### Stub

  - 인스턴스화하여 구현한 가짜 객체(=`Dummy`. *기능 구현 X*)를 이용해 **실제로 동작하는 것처럼 "보이게" 만드는 객체**입니다 
  - 해당 인터페이스 or 클래스를 **최소한으로** 구현합니다
  - 테스트에서 호출된 요청에 대해 미리 준비해둔 결과를 전달합니다

- ### Mock

  - 호출에 대한 기대를 명세하고, 내용에 따라 동작하도록 프로그래밍 된 객체입니다 
  - 테스트 작성을 위한 환경 구축이 어려울 때, 테스트하고자 하는 코드와 엮인 객체들을 대신하기 위해 만들어진 객체입니다

<br>



### Stub과 Mock의 차이점

> 참고 사이트 : http://martinfowler.com/articles/mocksArentStubs.html
>
> ---
>
> Of these kinds of doubles, only **mocks** insist upon `behavior verification`. The **other doubles** can, and usually do, use `state verification`. Mocks actually do behave like other doubles during the exercise phase, as they need to make the SUT believe it's talking with its real collaborators - but mocks differ in the setup and the verification phases.

사람들이 쉽게 목 오브젝트와 스텁을 혼동하곤 하지만,  **목 오브젝트**는 **행위 검증**(behavior verification)을 사용하고, **stub**을 포함한 다른 대역들은 **상태 검증**(state verification)을 사용합니다.

- `상태 검증` : **메소드가 수행된 후, 객체의 상태를 확인**하여 올바르게 동작했는지를 확인하는 검증법입니다

- `행위 검증` :  메소드의 리턴 값으로 판단할 수 없는 경우 **특정 동작을 수행하는지**확인하는 검증법입니다

  휴... 찾다보니 **행위 검증**의 경우, 말뿐으로 설명하기 보단 예시를 보여드리며 설명드리는 게 맞는 것 같습니다.

  아래는 메일 서비스 **스텁**을 이용한 **상태 검증** 샘플을 먼저 보겠습니다 

  ```java
  public interface MailService {
    public void send (Message msg);
  }
  // 메일 서비스를 테스트 하기 위해 추가적으로 메소드 만들어짐
  public class MailServiceStub implements MailService {
    private List<Message> messages = new ArrayList<Message>();
    public void send (Message msg) {
      messages.add(msg);
    }
    public int numberSent() {
      return messages.size();
    }
  }
  
  class OrderStateTester...
  
    public void testOrderSendsMailIfUnfilled() {		// 상태 검증
      Order order = new Order(TALISKER, 51);
      MailServiceStub mailer = new MailServiceStub();
      order.setMailer(mailer);
      order.fill(warehouse);
      assertEquals(1, mailer.numberSent());		// 올바른 상태 값이 나오는지 체크(테스트)
    }
  ```

  코드를 정확히 볼 필요는 없지만, **Stub을 이용하는 경우**는 `testOrderSendsMailIfUnfilled` 테스트를 위해 **추가적인 메소드들을 만들어서 테스트를 검증**했어야만 했습니다.

  이번에는 **목 오브젝트**를 이용한 **행위 검증** 샘플입니다.

  ```java
  class OrderInteractionTester...
  
    public void testOrderSendsMailIfUnfilled() {
      Order order = new Order(TALISKER, 51);
      Mock warehouse = mock(Warehouse.class);
      Mock mailer = mock(MailService.class);
      order.setMailer((MailService) mailer.proxy());
  
      mailer.expects(once()).method("send");
      warehouse.expects(once()).method("hasInventory")
        .withAnyArguments()
        .will(returnValue(false));
  
      order.fill((Warehouse) warehouse.proxy());
    }
  }
  ```

  행위 검증의 샘플의 경우, 

  값을 구체적으로 비교하지 않지만 목 오브젝트의 지원을 받아 별도의 코드 없이 **메소드 호출 여부 등을 간단하게 검사**할 수 있습니다. 

  (특정 동작이 수행되었는지 여부를 통해 로직 수행에 대한 판단을 내립니다)

<br>
<br>
<br>
<br>
직역하며 정리해서 틀린 부분이 존재할 수 있습니다. 질문 있으면 코멘트 남겨주세요. 확인하겠습니다



> 참고 사이트
>
> - https://medium.com/@SlackBeck/mock-object%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B0%80-85159754b2ac
>
> - https://beomseok95.tistory.com/295

**Comment by ksw6169** [comment]
안녕하세요. 남기신 코멘트 확인하였습니다.
작성하시느라 고생하셨습니다.
