### ISSUE TITLE
(7주차) 프록시 패턴과 데코레이터 패턴의 차이점

### ISSUE THREAD

**Issue by ksw6169** [team-tancheon/book-lounge#17]
@ririkat 님
프록시 패턴과 데코레이터 패턴의 차이점에 대해 설명해주세요.

**Comment by ririkat** [comment]
@ksw6169 님
답변 드리겠습니다.

<br/>

우선 두 디자인 패턴 모두
- 프록시를 사용하는 디자인 패턴

이라는 공통점이 있습니다.

<br/>

이 두 패턴의 큰 차이점은 프록시 사용목적과 타깃 오브젝트의 생성 시점에 있습니다.

<br/>

### 💡 프록시 패턴
- 프록시의 사용 목적 = `접근 방법 제어`
- 타깃의 **기능 자체에는 관여하지 않고**, 클라이언트가 타깃에 **접근하는 방식을 변경**해줌
- 오브젝트 생성 시점 = 요청 시 생성
   - 오브젝트의 생성 시점을 최대한 늦출 수 있음
- 사용 예) 원격 오브젝트 이용하는 경우(RMI,EJB, 리코팅 기술 등) , 타깃에 대한 접근권한 제한 (읽기모드 등)

<br/>

### 💡 데코레이터 패턴
- 프록시의 사용 목적 = `부가기능 부여`
- 타깃에 부가적인 기능을 런타임 시 다이나믹하게 부여해주기 위해 프록시를 사용하는 패턴
- 오브젝트 생성 시점 = 런타임 시점
   - 런타임 시 다이나믹하게 조합하여 사용 가능
- 사용 예)  라인넘버+ 컬러+페이징(부가기능)+소스코드 출력기능(핵심기능)  처럼 다양한 부가기능을 다이나믹하게 부여할 때 사용

<br/>

위에 간략하게 설명했듯이
두 패턴의 가장 큰 차이점은 프록시의 사용 목적이
`접근제어` 에 집중된 패턴인지
 `부가기능추가` 에 집중된 패턴인지가 가장 큰 차이점이라고 볼 수 있습니다.

<br/>

설명이 이해되지 않거나 오류가 있으면 comment 부탁드립니다.
감사합니다.

<br/>

**Comment by ksw6169** [comment]
@ririkat 
답변해주신 사항 확인하였습니다.
감사합니다.
