### ISSUE TITLE
(7주차) 프록시 패턴 적용 및 혼용

### ISSUE THREAD

**Issue by ririkat** [team-tancheon/book-lounge#18]
@KOO-YS 님
프록시 패턴이 적용되는 대표적인 3가지 경우와
데코레이션 패턴과 프록시 패턴의 혼용될 수 있는 이유가 무엇인지 설명해주세요

<br/>

감사합니다.

**Comment by KOO-YS** [comment]
안녕하세요 @ririkat 님
<br>
우선 먼저 프록시 패턴에 대해 간단하게 설명을 하고 넘어가자면,

**일반적으로** `프록시`는 클라이언트와 사용 대상 사이에 대리 역할을 맡은 오브젝트를 두는 방법이라고 총칭하며,

**디자인 패턴에서 말하는** `프록시 패턴`은  프록시를 사용하는 방법 중에서 타깃에 대한 접근 방법을 제어하려는 목적을 가진 경우를 말합니다.

<br>

<br>

책에서 언급된, 프록시 패턴이 적용될 수 있는 3가지에 대해 말씀드리겠습니다 

<br>

#### 1. 타겟 오브젝트에 대한 레퍼런스가 미리 필요할 경우

> 타깃 오브젝트를 생성하기가 복잡하거나 당장 필요하지 않은 경우에는 꼭 필요한 시점까지 오브젝트를 생성하지 않도록 권장됩니다.
>
> *하지만,* 타겟 오브젝트에 대한 레퍼런스가 미리 필요헐 경우, **실제 타깃을 만드는 대신 프록시를 넘겨주면 됩니다.** 

<br>

#### 2. 원격 오브젝트를 이용하는 경우

> 각종 리모팅 기술을 이용해 다른 서버에 존재하는 오브젝트를 사용해야 한다면, 원격 오브젝트에 대한 프록시를 만들어두고, 클라이언트는 프록시를 로컬에 존재하는 오브젝트처럼 사용할 수 있습니다. 

<br>

#### 3. 특별한 상황에서 타깃에 대한 접근권한을 제어할 경우 

> 특정 오브젝트에 대한 접근제한을 강제하고 싶다면 프록시를 만들어 특정 메소드에 접근할 경우 예외를 발생시킬 수 있습니다.
>
> ##### ex) Collections의 unmodifiableCollection() : 전형적인 접근권한 제어용 프록시

<br>

이렇게 타깃의 기능 자체에 관여하지 않으면서 접근하는 방법을 제어할 때, 프록시 패턴을 이용합니다.

<br>

---

<br>

 `프록시 패턴`은 **인터페이스를 통해 위임하는 방식**으로 만들었을 때, `데코레이션 패턴과 혼용`이 가능합니다. 

인터페이스를 통해 다음 호출 대상으로 접근할 때,

 **그 사이에** 또 다른 프록시나 데코레이터를 **계속해서 추가**할 수 있는 장점이 있습니다.

<br>

<br>

답변이 잘 이해가 안간다면 코멘트 남겨주세요! 감사합니다 :)
