### ISSUE TITLE
(7주차) 자바 리플렉션이란

### ISSUE THREAD

**Issue by KOO-YS** [team-tancheon/book-lounge#19]
안녕하세요 @ksw6169 님
이번주 본문 중에서 **다이나믹 프록시**를 **리플랙션 기능**을 이용해서 만들어 보았는데요

자바에서 
1. 리플랙션`Reflection`의 개념 설명과 
2. 왜 리플렉션이 사용되곤 하는지
3. 또 리플랙션을 사용해 Class 객체를 얻는 법을 코드로 짧게 보여주세요 :)

**Comment by ksw6169** [comment]
안녕하세요. 
@KOO-YS 님 답변드립니다.

<br>

## Q1. Reflection의 개념
- Reflection은 Java에서 제공하는 기능으로 `java.lang.reflect` 패키지를 이용해 특정 클래스가 가진 필드, 생성자, 메소드 등의 정보를 조회하거나 사용할 수 있도록 해주는 기능을 말합니다.
- Reflection이 가능한 이유는 아래와 같습니다.
    - 자바 컴파일러에 의해 생성된 바이트코드(*.class) 는 클래스 이름, 상속관계, 클래스 타입, 메소드, 생성자, 멤버변수 등에 대한 정보를 가집니다.
    - 바이트코드는 JVM 클래스로더에 의해 분석되어 메모리에 로드(JVM Method Area에 저장)되는데 이 과정에서 `java.lang.Class` 객체를 생성하여 저장합니다. (Class 객체는 클래스의 모든 정보를 담고 있습니다.)
    - Class 객체는 특정 클래스에 대한 모든 정보를 가지고 있기 때문에 클래스의 이름만 알고 있다면 언제든 이 영역을 뒤져서 클래스에 대한 정보를 조회하거나 클래스가 가진 멤버, 메소드 등을 사용할 수 있습니다.

<br>

## Q2. Reflection을 사용하는 이유
- 개발자가 작성한 클래스의 정보를 이용해 객체를 동적으로 생성, 관리, 사용하기 위해 사용합니다.
- 일반적으로 개발자가 직접 Reflection을 사용하는 경우는 드물고, 프레임워크나 라이브러리에서 주로 사용합니다.
- 예를 들어 Spring Framework에서 `@Component` Annotation(`@Controller`, `@Service`, `@Repository`) 을 사용한 클래스들을 스캔하고, 싱글톤으로 생성하여 프레임워크 상에서 관리해야 하는 경우에 Reflection 기능이 없다면 프레임워크에서는 개발자가 작성한 클래스가 무엇인지 알 수도 없고 생성할 수도 없습니다. 이 때 Reflection을 사용할 수 있다면 개발자가 작성한 클래스의 정보를 이용해 객체를 동적으로 생성하고 관리할 수 있으므로 Reflection을 사용합니다.

<br>

## Q3. Reflection을 사용해 Class 객체를 얻는 방법 - 코드

- Reflection 대상 클래스

```java
package com.corgi.mailer;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class User {
    private String email;
    private String password;
    private String name;
}
```

- Reflection 사용 코드
```java
package com.corgi.mailer.service;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;

@Slf4j
public class ReflectionTests {

    @Test
    void getClassTest() {
        try {
            Class c = Class.forName("com.corgi.mailer.User");
            System.out.println("class name : " + c.getName());

            Field[] fields = c.getDeclaredFields();

            for (Field field : fields) {
                System.out.println("field name : " + field.getName() + ", type : " + field.getType());
            }
        } catch (ClassNotFoundException e) {
            log.error(e.getMessage());
        }
    }
}
```

- 결과

```
class name : com.corgi.mailer.User
field name : email, type : class java.lang.String
field name : password, type : class java.lang.String
field name : name, type : class java.lang.String
```

<br>

궁금하신 사항은 코멘트로 남겨주세요. :)
