### ISSUE TITLE
(9주차) @PostConstruct

### ISSUE THREAD

**Issue by KOO-YS** [team-tancheon/book-lounge#25]
안녕하세요 @ksw6169 님~
<br>
이번 범위에서
어노테이션을 이용한 스프링 빈 설정에 관련하여 `@PostConstruct` 어노테이션이 등장했죠?
스프링 빈의 생명 주기 `초기화` 및 `종료` 시점 어노테이션과 `스프링 빈의 생명주기`에 대해 설명 부탁드립니다 :)

**Comment by ksw6169** [comment]
@KOO-YS 님 안녕하세요.
궁금하신 사항은 답변주시면 감사하겠습니다.

<br>

## Q. 스프링 빈의 생명주기에 대한 설명
- 스프링 빈은 `객체 생성 - 초기화 - 사용 - 소멸` 의 생명주기(Lifecycle)를 갖습니다.
- 스프링 컨테이너에 의해 객체가 생성되고, 의존성 주입까지 마친 빈을 대상으로 별도의 초기화 작업이 필요하다면 스프링이나 JSR-250에서 지원하는 방법을 이용해 빈에 대한 초기화 작업이 가능합니다.
- 이후에 해당 빈을 사용하고, 스프링 컨테이너가 종료되는 시점이 되면 빈 객체를 소멸하기 전에 스프링이나 JSR-250에서 지원하는 방법을 이용해 빈 객체에 대한 부가적인 작업을 수행할 수 있습니다. (ex. 리소스 반환 작업)

<br>

## Q. 스프링 빈의 초기화 시점 어노테이션
- 객체 생성 후 의존성 주입까지 마친 빈을 대상으로 스프링 빈을 초기화하는 방법은 3가지가 있습니다.
    - `@PostConstruct` annotation 이용
    - `InitializingBean` 인터페이스의 `afterPropertiesSet()` 메서드 구현
    - Spring XML Bean 설정 파일 혹은 `@Bean` 에 `init-method` 명시

<br>

### (1) `@PostConstruct` annotation을 이용
- `@PostConstruct` 를 메서드 위에 선언해주면 의존성 주입 이후에 지정한 메서드를 수행해줍니다.

```java
@Slf4j
@Service
public class UserService {
    private UserRepository userRepository;
		
    @Autowired
    public UserService(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    @PostConstruct
    public void postConstruct() {
        log.info("postConstruct!");
    }
}
```

- 이 annotation은 JSR-250에 명시된 annotation으로 JSR-250을 구현한 프레임워크, 라이브러리를 이용해 사용할 수 있습니다. 따라서 Spring framework에 종속되지 않고 사용할 수 있다는 장점이 있습니다.
- Spring 2.5 이후부터 사용이 가능합니다.

<br>

### (2) `InitializingBean` 인터페이스의 `afterPropertiesSet()` 메서드 구현
- Spring Framework에서 제공하는 인터페이스로 `afterPropertiesSet()` 를 구현하면 의존성 주입 이후에 Spring Container가 이 메서드를 호출하여 빈에 대한 초기화 작업을 수행해줍니다.

```java
@Slf4j
@Service
public class UserService implements InitializingBean {
    private UserRepository userRepository;

    @Autowired
    public UserService(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    @Override
    public void afterPropertiesSet() throws Exception {
        log.info("afterPropertiesSet!");
    }
}
```

<br>

### (3) Spring XML Bean 설정 파일 혹은 `@Bean` 에 `init-method` 명시

```java
@Slf4j
@Configuration
public class UserConfig {
    @Bean(initMethod = "initUser")
    public User user() {
        return new User();
    }

    private class User {
        public void initUser() {
            log.info("initUser!");
        }
    }
}
```

<br>

## Q. 스프링 빈의 소멸 시점 어노테이션

- 빈 소멸 시점에 별도의 작업을 수행하는 방법은 초기화 작업과 마찬가지로 3가지가 있습니다.
    - `@PreDestory` annotation 이용
    - `DisposableBean` 인터페이스의 `destory()` 메서드 구현
    - Spring XML Bean 설정 혹은 `@Bean` 에 `destroy-method` 명시

<br>

### (1) `@PreDestory` annotation을 이용

- `@PreDestroy` 를 메서드 위에 선언하면 빈 소멸 시점에 지정한 메서드를 수행해줍니다.

```java
@Slf4j
@Service
public class UserService {
    @PreDestroy
    public void preDestroy() {
        log.info("preDestory!");
    }
}
```

- `@PostConstruct` 와 마찬가지로 JSR-250 스펙으로 명시되어 있습니다. 마찬가지로 Spring 2.5 이후부터 사용이 가능합니다.

<br>

### (2) `DisposableBean` 인터페이스의 `destory()` 메서드 구현

- Spring Framework에서 제공하는 인터페이스로 `destory()` 를 구현하면 빈 소멸 시점에 이 메서드를 호출하여 빈에 대한 부가 작업을 수행해줍니다.

```java
@Slf4j
@Service
public class UserService DisposableBean {
    @Override
    public void destroy() throws Exception {
        log.info("destroy!");
    }
}
```

<br>

### (3) Spring XML Bean 설정 혹은 `@Bean` 에 `destroy-method` 명시

```java
@Slf4j
@Configuration
public class UserConfig {

    @Bean(destroyMethod = "destroyUser")
    public User user() {
        return new User();
    }

    private class User {
        public void destroyUser() {
            log.info("destroyUser!");
        }
    }
}
```

<br>

## 기타 - 호출 순서
- Spring Bean의 초기화/소멸 메서드의 호출 순서에 대한 예제 코드입니다. 참고 바랍니다.

```java
@Slf4j
@Configuration
public class UserConfig {

    @Bean(initMethod = "initUser", destroyMethod = "destroyUser")
    public User user() {
        return new User();
    }

    private class User implements InitializingBean, DisposableBean {
        @PostConstruct
        public void postConstruct() {
            System.out.println("postConstruct!");
        }

        @Override
        public void afterPropertiesSet() throws Exception {
            System.out.println("afterPropertiesSet!");
        }

        public void initUser() {
            System.out.println("initUser!");
        }

        @PreDestroy
        public void preDestroy() {
            System.out.println("preDestroy!");
        }

        @Override
        public void destroy() throws Exception {
            System.out.println("destroy!");
        }

        public void destroyUser() {
            System.out.println("destroyUser!");
        }
    }
}
```

```java
postConstruct!
afterPropertiesSet!
initUser!
preDestroy!
destroy!
destroyUser!
```

<br>

## 주의 사항
- scope가 prototype으로 지정된 경우 위의 메서드들이 전부 동작하지 않습니다.

<br>

## 참고 자료
- [스프링 빈 생명주기(Bean Lifecycle) 메서드와 실행 순서](https://madplay.github.io/post/spring-bean-lifecycle-methods)
- [Spring Bean Life Cycle (빈 생명주기 관리)](https://javaslave.tistory.com/48)
- [Spring - Bean 초기화 및 생명주기](https://unabated.tistory.com/entry/Spring-Bean-%EC%B4%88%EA%B8%B0%ED%99%94-%EB%B0%8F-%EC%83%9D%EB%AA%85%EC%A3%BC%EA%B8%B0)
- [Spring 빈/컨테이너 생명주기 (Lifecycle)](https://flowarc.tistory.com/entry/Spring-%EB%B9%88%EC%BB%A8%ED%85%8C%EC%9D%B4%EB%84%88-%EC%83%9D%EB%AA%85%EC%A3%BC%EA%B8%B0-Lifecycle)
