### ISSUE TITLE
[아이템 7] 참조를 담은 변수를 유효 범위 밖으로 밀어내는 것

### ISSUE THREAD

**Issue by yuhyeminn** [team-tancheon/book-lounge#29]
> p38.
다 쓴 참조를 해제하는 가장 좋은 방법은 그 참조를 담은 변수를 유효 범위(scope) 밖으로 밀어내는 것이다. 여러분이 변수의 범위를 최소가 되게 정의했다면 이 일은 자연스럽게 이뤄진다.

다 쓴 참조를 담은 변수를 유효 범위 밖으로 밀어낸다라는 것은 어떤 동작을 얘기하는 걸까요?..

**Comment by ksw6169** [comment]
"다 쓴 참조를 담은 변수를 유효 범위 밖으로 밀어낸다." 는 내용에서 유효 범위는 변수의 유효 범위를 의미하는데요. 
(지역 변수는 변수가 선언된 block 이 유효 범위가 되겠죠) 

유효 범위를 벗어난 변수는 자연스럽게 가비지 컬렉션의 대상이 됩니다.

따라서 "다 쓴 참조를 담은 변수를 유효 범위 밖으로 밀어낸다" 라는 동작은
"변수의 유효 범위를 지정해 유효 범위를 벗어났을 때 가비지 컬렉션의 대상이 되도록 만드는" 동작을 의미합니다.

예를 들어 아래 test() 메소드에서 User라는 지역 변수를 선언했는데, test() 메소드가 종료되면 User 지역 변수는 자연스럽게 소멸되겠죠.

```java
public class Example {

    public static void main(String[] args) {
        test();
    }

    public static void test() {

        User user = User.builder()
                .id(1L)
                .email("test@naver.com")
                .password("testPassword")
                .name("sungwon")
                .build();

        System.out.println("user id : " + user.getId());
    }
}
```

설명드린 내용이 이해가 되지 않거나 추가로 궁금하신 사항 있으시면 코멘트 부탁드립니다.
