### ISSUE TITLE
(1주차) 스프링의 빈 오브젝트 관리 방식 

### ISSUE THREAD

**Issue by ririkat** [team-tancheon/book-lounge#3]
@KOO-YS 연수님

스프링의 빈 오프젝트 관리 방식과 (기본 관리 방식)
그러한 방식으로 관리하는 이유를 스프링의 환경적 요인과 연결하여 설명해 주세요.

**Comment by KOO-YS** [comment]
네 안녕하세요 주말 잘 보내고 계신가요 @ririkat 별리님

질문 답변하겠습니다 👍 

**스프링 컨테이너**는 기본적으로 빈을 `싱글톤`으로 생성합니다
빈 오브젝트는 컨테이너가 실행될 때 딱 한 개의 인스턴스가 생성되고 컨테이너가 종료될 때까지 유지되다가 소멸합니다.
 
싱글톤 방식이 아닌 다른 방식으로 빈을 생성할 수 있지만, 
스프링이 **기본적으로 빈을 싱글톤으로 관리함**으로써 이점을 얻을 수 있습니다

**싱글톤 빈 관리 환경의 이점** 🍯 
1. 여러번 참조될 때마다 새로운 인스턴스가 생성되지 않고 기존에 캐시되어 있는 인스턴스를 반환하기 때문에 시간적, 공간적 이점이 있습니다
    > [ in detail ]
    > 빈은 stateless 방식으로 관리되어야합니다
    > 무상태 객체는 동기화 비용이 없고, 매번 또다른 인스턴스를 생성해 참조할 필요가 없습니다
    > 
    > 생성된 빈은 `single beans cache`에 저장되며 빈에 대한 요청이 있을때 여기에 캐시된 객체를 반환합니다

2. 빈의 각 생명주기(생성부터 소멸까지) 기능을 추가하거나 미리 검사할 수 있습니다
    -> 라이프 사이클 관리가 유용합니다.

3. 개발자가 직접 빈을 생성하지 않고 가져다 쓰는 방식을 통해 객체의 의존성을 관리해 줄 수 있습니다

별리님 질문 의도와 맞는 답변이 되었나요? 
궁금한 점 있다면 코멘트 달아주세요 🍺 
감사합니다
# 🐤
