### ISSUE TITLE
[아이템 7] 메모리 누수(Memory Leak) : GC가 회수하지 못하는 경우

### ISSUE THREAD

**Issue by KOO-YS** [team-tancheon/book-lounge#30]
이번 Item 7에서 우리는 메모리 누수와 다 쓴 객체 참조를 해제하는 방식으로 메모리 관리에 신경쓰는 방법을 배웠습니다.
<br>

메모리 누수는 겉으로 잘 드러나지 않아 시스템에 수년간 잠복하기도 하는데요,
<br>

우리가 신경쓰고 예방해야할 메모리 누수는 어떤 경우들에 발생할까요?
 **가비지 컬렉터(Garbage Collector)가 해체하지 못하는 패턴 or 참조 객체**의 사례를 3가지 이상 알려주세요 🥰

**Comment by ksw6169** [comment]
메모리 누수가 발생하는 패턴은 다음과 같습니다.

**1. 오토박싱에 의해 무의미한 객체를 생성하는 경우**
```java
public long sum() {
    Long sum = 0L;

    for (int i=0; i<Integer.MAX_VALUE; i++) {
        sum = sum + i;
    }

    return sum;
}
```

<br>

**2. 메모리 캐시에 데이터를 넣고 이를 지우지 않는 경우**
```java
private Map<String, String> map = new HashMap<>();

public void initCache() {
    map.put("key1", "value1");
    map.put("key2", "value2");
    map.put("key3", "value3");
}
```

<br>

**3. 스트림 객체를 사용하고 닫지 않은 경우**
```java
public void test() {
    try {
        Connection con = DriverManager.getConnection();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
```

더 자세한 내용은 아래 링크 참고 부탁드립니다. 
이해가 되지 않거나, 궁금하신 사항 코멘트로 남겨주시면 감사하겠습니다.

https://junghyungil.tistory.com/133

**Comment by Hyung1Jung** [comment]
잘 보고 갑니다~
