### ISSUE TITLE
[아이템 13] HashTable

### ISSUE THREAD

**Issue by KOO-YS** [team-tancheon/book-lounge#33]
Item 13에서 우리는 가변 객체를 참고하는 필드를 가진 객체 clone() 메소드 구현의 예제로  `HashTable` 코드를 확인할 수 있었습니다.
이번 주 스터디 내용에 포함된 `Item 11 hashCode` 내용과 `Item 13의 HashTable`의 내용을 보면서 한번 Hash에 대해 짚어가는 시간이 되었으면 좋겠는데요!
<br>

> 🔔 Hash 테이블은 **적은 메모리로 최대한 데이터를 분포시켜서 저장**하기 위해, 실제로 사용하는 키 개수보다 적은 해시 테이블을 운용하는데, 그러다보니 **해시 충돌이 발생할 수 밖에 없습니다**.

<br>

### Hash 함수에서 최대한 적은 해시 테이블을 운용하면서 해시 충돌을 해결하기 위해 고안된 방법 2가지를 설명해주세요
<br>

**Comment by yuhyeminn** [comment]
먼저 해시 충돌이란 해시 함수로 해시를 만드는 과정에서 서로 다른 key가 같은 해시값으로 변경되어서 같은 공간에 2개의 value가 저장되는 현상입니다. 이 현상은 key-value가 1:1로 매핑되어야 하는 해시 테이블의 특성에 위배됩니다.

해시 충돌이 일어났을 경우 해결하는 방법은 여러가지가 있습니다.

### 1. Chaining

해시 충돌이 발생하면 연결 리스트로 데이터들을 연결하는 방식입니다. 

![image](https://user-images.githubusercontent.com/58774719/127772279-12cb94af-8dc9-4b07-97b8-4dc0cad7222e.png)


이 그림을 보면 Sandra Dee라는 사람의 연락처를 삽입할 때, 충돌이 일어나기 때문에 버킷 내에서 연결리스트로 데이터를 연결하는 것을 확인 할 수 있습니다. 

체이닝은 **한정된 버킷을 효율적으로 사용 가능**하고, 해시충돌 시 연결 리스트로 연결만 해주면 되기 때문에 **해시 함수를 선택하는 중요성이 상대적으로 적다**는 장점이 있습니다. 반면에, 한 hash에 **쏠림현상이 발생한다면 검색 효율이 낮아질 수 있고**, **별도의 동적인 공간을 할당해줘야 한다**는 단점이 있습니다.

<br/>
 
### 2. 개방 주소법(Open Addressing)

개방 주소법은 해시 충돌이 발생할 경우 비어있는 hash를 찾아 데이터를 삽입하는 방식입니다. 

![image](https://user-images.githubusercontent.com/58774719/127772289-978b6433-55cb-4344-b111-36d10a545ede.png)

개방 주소법에는 대표적으로 3가지가 있습니다.

- 선형 탐색(Linear Probing) : 해시 충돌 시 **다음 버킷, 혹은 몇 개를 건너뛰어 데이터를 삽입**한다.
- 제곱 탐색(Quadratic Probing) : 해시 충돌 시 **제곱만큼 건너뛴 버킷에 데이터를 삽입**한다. (1, 4, 9, 16, ... )
- 이중 해시(Double Hashing) : 해시 충돌 시 **다른 해시함수를 한 번 더 적용한 결과를 이용**한다.

개방 주소법을 이용하면 **체이닝처럼 포인터가 필요 없고**, **지정한 메모리 외 추가적인 저장공간도 필요 없다**는 장점이 있습니다.  반면에, **해시 함수의 성능에 따라 해시테이블의 성능이 좌우**되며, **데이터가 늘어난다면 그에 해당하는 버킷을 마련 해 둬야한다**는 단점이 있습니다.

<br/>
 

요약하자면 Chaining은 해시 테이블의 크기를 유연하게 사용하며 충돌을 해결하고, Open Addressing은 해시테이블의 크기는 고정시키되 데이터를 삽입할 위치를 잘 찾는데에 집중한 해시 충돌 해결방법이라고 보시면 됩니다.

<br/>
 
추가적인 내용은 첨부한 링크 참고 부탁드립니다 🙏
<br/>
 

> [[자료구조] 해싱, 해시 테이블 그리고 Java HashMap - adam2님의 velog](https://velog.io/@adam2/%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0%ED%95%B4%EC%8B%9C-%ED%85%8C%EC%9D%B4%EB%B8%94#%ED%95%B4%EA%B2%B0-%EB%B0%A9%EB%B2%95)
> [해시(Hash)와 해시충돌(Hash Collision) - preamtree님의 blog](https://preamtree.tistory.com/20)
