### ISSUE TITLE
[아이템 17] 가변 동반 클래스 / 다단계 연산

### ISSUE THREAD

**Issue by ksw6169** [team-tancheon/book-lounge#34]
> 110p 내용 中<br>
>
> 원하는 객체를 완성하기까지의 단계가 많고, 그 중간 단계에서 만들어진 객체들이 모두 버려진다면 성능 문제가 더 불거진다. 이 문제에 대처하는 방법은 두 가지다. 첫 번째는 **흔히 쓰일 다단계 연산들을 예측하여 기본 기능으로 제공하는 방법이다. 이러한 다단계 연산을 기본으로 제공한다면 더 이상 각 단계마다 객체를 생성하지 않아도 된다.** 불변 객체는 내부적으로 아주 영리한 방식으로 구현할 수 있기 때문이다. 예컨대 BigInteger는 모듈러 지수 같은 다단계 연산 속도를 높여주는 가변 동반 클래스(companion class)를 package-private으로 두고 있다. 

<br>

다단계 연산과 가변 동반 클래스 관련한 내용인데 이해가 잘 안되서 질문 드립니다. 

<br>

**1. 흔히 쓰일 다단계 연산들을 예측하여 기본 기능으로 제공하는 방법이다. 이러한 다단계 연산을 기본으로 제공한다면 더 이상 각 단계마다 객체를 생성하지 않아도 된다.**
- 불변 클래스에서 다단계 연산을 단계별로 제공한다면 각 연산에서는 새로운 불변 객체가 생성되어야 하지 않나요? 책의 내용대로라면 단계별 연산의 결과로 매번 불변 객체를 생성해서 반환하는 것이 아니라, 연산된 결과를 담고 있는 다른 클래스(가변 동반 클래스)를 반환하고, 다단계 연산이 모두 완료되면 그제서야 불변 객체를 생성해서 반환한다는 것인지.. 궁금합니다.

<br>

**2. 가변 동반 클래스가 무엇인가요?**
- 제곧내입니다. 가변 동반 클래스가 무엇인지 설명 부탁드립니다ㅠㅠ..

**Comment by ririkat** [comment]
#### 불변 클래스

그 인스턴스의 내부 값을 수정할 수 없는 클래스로, 인스턴스 내 간직된 정보는 고정되어 객체가 파괴되는 순간까지 절대로 변경되지 않는다.

##### 불변 클래스 특징

- 근본적으로 스레드 안전하여 따로 동기화할 필요가 없으며, 쓰레드 간에 영향을 줄 수 없기 때문에 안심하고 공유할 수 있다.
- 불변 객체 끼리는 내부 데이터를 공유할 수 있다.
- 객체를 만들 때 다른 불변 객체들을 구성요소로 사용하면 이점이 많다.
- 불변 객체는 그 자체로 실패 원자성을 제공한다.
  상태가 절대 변하지 않으니 잠깐이라도 불일치 상태에 빠질 가능성이 없다.
- 계산 비용이 큰 값을 처음 쓰일 때 계산하여 final이 아닌 필드에 캐시해놓음으로써 동일 값 요청시 캐시해둔 값을 반환해 계산 비용을 절감한다.
- 불변으로 만들 수 없는 클래스라도 변경할 수 있는 부분을 최소한으로 줄이자.
- 생성자는 불변식 설정이 모두 완료된, 초기화가 완벽히 끝난 상태의 객체를 생성해야 한다.
- **값이 다르면 반드시 독립된 객체로 만들어야 한다.**



#### 가변 동반 클래스

불변 클래스가 비즈니스 로직 연산 등 시간 복잡도가 높은 연산 시 불필요한 클래스 생성을 막기 위해 불변 클래스의 연산을 예측하여 내부적으로 연산 처리를 해주는 가변 클래스를 사용하는데 이 클래스를 가변 동반 클래스라고 한다.



#### 다단계 연산

단계를 갖고 이루어지는 연산



<br/>



:question:  흔히 쓰일 다단계 연산들을 예측하여 기본 기능으로 제공하는 방법이다. 이러한 다단계 연산을 기본으로 제공한다면 더 이상 각 단계마다 객체를 생성하지 않아도 된다.

- 불변 클래스에서 다단계 연산을 단계별로 제공한다면 각 연산에서는 새로운 불변 객체가 생성되어야 하지 않나요? 책의 내용대로라면 단계별 연산의 결과로 매번 불변 객체를 생성해서 반환하는 것이 아니라, 연산된 결과를 담고 있는 다른 클래스(가변 동반 클래스)를 반환하고, 다단계 연산이 모두 완료되면 그제서야 불변 객체를 생성해서 반환한다는 것인지.. 궁금합니다.



<br/>



:arrow_forward: 위 불변 클래스 특징 중 **값이 다르면 반드시 독립된 객체로 만들어야 한다** 는 특징으로 인해 다단계 연산과 같은 복잡도가 높은 연산 시 불변 객체가 불필요하게 생성되는 문제가 있습니다. 이러한 문제를 해결하기 위해 불변 클래스와 기능은 같지만 가변적인 클래스를 제공하여 이를 해결하는데요. (= 가변 동반 클래스) 가변 동반 클래스는 불변 클래스가 아닌 가변 클래스이기 때문에 불필요한 생성 문제를 해결해 줍니다. 연산 시에 가변 동반 클래스를 이용하여 연산하

질문하신 내용에 대한 답은 String 문자열 붙이는 방법들의 동작 방식 차이를 통해 확인 하실 수 있습니다. 아래 링크 참고 부탁드립니다.

- (+, concat, StringBuilder, StringBuffer) 의 차이 : [https://junghn.tistory.com/entry/JAVA-%EB%AC%B8%EC%9E%90%EC%97%B4-%EB%B6%99%EC%9D%B4%EB%8A%94-%EB%B0%A9%EB%B2%95concat-StringBuilder-StringBuffer](https://junghn.tistory.com/entry/JAVA-%EB%AC%B8%EC%9E%90%EC%97%B4-%EB%B6%99%EC%9D%B4%EB%8A%94-%EB%B0%A9%EB%B2%95concat-StringBuilder-StringBuffer)


추가로 +연산 동작 방식을 통한 불변 클래스가 다단계 연산을 처리할 때 가변 동반 클래스를 어떻게 활용하는지 확인할 수 있는 내용에 대한 참고 링크로 첨부합니다.

+ +연산 동작 방식 : [https://codingdog.tistory.com/entry/java-string-%EC%97%B0%EC%82%B0-%EC%96%B4%EB%96%BB%EA%B2%8C-%EB%8F%99%EC%9E%91%ED%95%98%EB%8A%94%EC%A7%80-%EC%95%8C%EC%95%84%EB%B4%85%EC%8B%9C%EB%8B%A4](https://codingdog.tistory.com/entry/java-string-%EC%97%B0%EC%82%B0-%EC%96%B4%EB%96%BB%EA%B2%8C-%EB%8F%99%EC%9E%91%ED%95%98%EB%8A%94%EC%A7%80-%EC%95%8C%EC%95%84%EB%B4%85%EC%8B%9C%EB%8B%A4) 


<br/>

:question: 가변 동반 클래스가 무엇인가요?

:arrow_forward: 불변 클래스가 비즈니스 로직 연산 등 시간 복잡도가 높은 연산 시 불필요한 클래스 생성을 막기 위해 불변 클래스의 연산을 예측하여 내부적으로 연산 처리를 해주는 가변 클래스를 사용하는데 이 클래스

**Comment by ksw6169** [comment]
넵 남겨주신 코멘트 이해했습니다. 감사합니다! :D
