### ISSUE TITLE
(1주차) 스프링 빈의 스코프

### ISSUE THREAD

**Issue by KOO-YS** [team-tancheon/book-lounge#4]
@ririkat 별리님
스프링의 빈은 특별한 설정없이 싱글톤 범위를 갖습니다. 
싱글톤 범위의 빈을 생성해 사용할 시 주의해야할 점을 설명하고, 
싱글톤 범위에 적합하지 않은 빈의 경우를 고민해보세요.

**Comment by ririkat** [comment]
스프링은 특별한 설정이 없다면 오브젝트를 싱글톤으로 관리하는데요.

이 말은 특별한 설정이 들어간다면 싱글톤이 아닌 다른 방식으로도 관리할 수 있다는 것을 뜻합니다.

1.6.3 마지막에 빈 스코프를 이야기하는 부분에서도 간략히 설명되어 있는 부분이기도 하죠.



##### 그렇다면, 싱글톤에 적합한 객체는 무엇이고, 적합하지 않은 객체는 무엇일까요?

이를 판단하기 위해서는 먼저 싱글톤이 무엇인지부터 바로 알아야 합니다.

- Singleton (싱글톤)

  > 어플리케이션 내의 특정 클래스를 하나만 존재하도록 강제하는 패턴
  >
  > - 단일 오브젝트만 존재해야함
  > - 어플리케이션 내에서 하나의 오브젝트를 공유함

싱글톤은 위에 설명한 대로 어플리케이션 내에서 하나의 오브젝트만 존재하도록 강제하는 방식으로

싱글톤 빈은 Spring 컨테이너에서 한 번 생성되면 컨테이너가 사라지기 전까지 존재하게 되고, 해당 빈에 대한 요청과 호출 시에는 캐시된 데이터를 반환하는 방식으로 동작하게 됩니다.

****

#### 싱글톤으로 적합한 객체

- 상태가 없는 공유 객체 (무상태 방식)
- 상태유지 방식 (읽기 전용)
- 공유가 필요한 상태를 지닌 공유 객체
- 사용빈도가 매우 높은 객체

****

위와 같이 싱글톤은 단일 오브젝트라는 특징 때문에 전역적으로 공유되고 쓰기보다는 읽기 전용의 객체에게 적합합니다.


싱글톤은 위에서 언급된 것 처럼 전역성을 띄면서 다른 객체와 공통으로 사용하는 경우와 같은 케이스에서는 효율적인 방식이지만 그 외에는 문제점이 생길 수 있습니다.

****

#### 싱글톤 사용시 주의할 점

- 싱글톤으로 만든 객체의 역할이 복잡한 경우라면 해당 싱글톤 객체를 사용하는 **다른 객체간의 결함도**가 높아져서 객체 지향 설계 원칙에 어긋나게 됩니다. (객체의 역할이 복잡한 경우는 사용 지양)
- 싱글톤 객체를 수정할 경우 싱글톤 객체를 사용하는 곳에서 **사이드 이팩트** 발생 확률이 생기게 되며, **멀티 쓰래드**환경에서 동기화 처리 문제등이 생기게 됩니다. (쓰기를 하지 않도록 주의)

****




위처럼 싱글톤 사용시에 효율이 떨어지거나 문제가 생기는 싱글톤에 적합하지 않은 객체는 다른 스코프로 관리되어져야 합니다.

##### 그렇다면, 싱글톤에 적합하지 않은 객체란 무엇일까요?

싱글톤에 적합하지 않은 객체는 싱글톤에 적합한 객체의 특징들과 반대되는 특성을 생각해보면 됩니다.

****

#### 싱글톤으로 적합하지 않은 객체

- 쓰기가 가능한 상태를 지닌 객체

  쓰기가 가능한 상태가 많아서 동기화 비용이 객체 생성 비용보다 크다면 싱글톤으로 적합하지 않다.

- 상태가 노출되지 않은 객체

  일부 제한적인 경우, 내부 상태를 외부에 노출하지 않는 빈을 참조하여 다른 의존객체와는 독립적으로 작업을 수행하는 의존 객체가 있다면 싱글톤보다 비싱글톤 객체를 사용하는 것이 더 나을 수 있다.

****

싱글톤의 가장 큰 특징은 새 객체 생성여부와 공유 여부에 있습니다.

이를 뒤집어 생각해보면 새로운 객체가 생성되어야 하는 경우와 공유되지 않아야 하는 경우에는 싱글톤에 적합하지 않다는 것을 알 수 있습니다.



이정도면 답변이 되었을까요? 답변에 오류가 있거나 의견이 있으시면 코멘트 부탁드립니다.
