### ISSUE TITLE
(2주차) @RunWith 어노테이션이란?

### ISSUE THREAD

**Issue by ksw6169** [team-tancheon/book-lounge#5]
@ririkat 님

JUnit4를 이용해 스프링 프레임워크에서 ApplicationContext를 사용하는 로직을 테스트한다고 했을 때, 
`@RunWith` 어노테이션을 사용하던데.. 이 어노테이션의 기능이 무엇인가요? 
`@RunWith`에서 지정하는 테스트러너가 어떤 역할을 수행하는지까지 알려주시면 감사하겠습니다 :)

**Comment by ririkat** [comment]
@ksw6169 님
등록하신 이슈에 대한 답변 드리겠습니다!
<br/>
#### 💡 `@RunWith` 어노테이션을 사용하던데.. 이 어노테이션의 기능이 무엇인가요?

 `@RunWith` 는 JUnit의 기능을 확장해서 관련 기능을 사용하게끔 해주는 어노테이션입니다.

일반 클래스의 클래스 작업을 실행해주는 main 클래스와 같은 기능을하는 JUnit의 클래스를 러너 클래스라고 부르는데 테스트는 이 러너확장클래스를 이용하여 진행됩니다.

때문에 `@RunWith(러너확장클래스)` 형식으로 선언하여 사용합니다.

###### 선언 형식 예제

```java
// SpringJUnit4ClassRunner.class : 스프링 프레임워크에서 제공하는 JUnit의 러너클래스를 확장한 클래스
@RunWith(SpringJUnit4ClassRunner.class)
```

<br/>

#### 💡 `@RunWith`에서 지정하는 테스트러너가 어떤 역할을 수행하하는지?

###### 테스트 러너(Test Runner)

> 테스트 클래스들의 객체들을 생성하고, 각각의 테스트 메소드를 실행하여 그 결과를 보여주는 테스트 실행 클래스

`@RunWith`에서 지정하는 테스트러너는 JUnit에 기본 내장된 테스트 러너인 BlockJUnit4ClassRunner를 확장한 클래스들을 이용합니다.

대표적인 예로 아래 두가지의 테스트 러너가 있습니다.

- `SpringJUnit4ClassRunner` : 스프링프레임워크에서 제공하는 테스트 러너 클래스

  > 스프링에서 자체적으로 만들어놓은 추가적인 테스트 기능을 이용할 수 있게 해줍니다.
  >
  > - @Repeat
  > -  @ProfileValueSourceConfiguration
  > - @IfProfileValue
  > - ...

- `SuiteClasses` : JUnit 내부 확장 러너 클래스

  > 여러 개의 테스트 클래스를 일괄적으로 수행할 수 있게 해줍니다.

  ```java
  @RunWith(Suite.class)
  // Test1.class, Test2.class, Test3.class 를 순차적으로 테스트 실행해줌.
  @SuiteClasses(Test1.class, Test2.class, Test3.class)
  ```

 <br/>

##### ✏️ JUnit 버전업에 따른 `@RunWith`의 대체

`@RunWith` 어노테이션은 최신 버전의 스프링 부트에서는 와서는 잘 사용하지 않습니다.

JUnit 5.x 버전에 와서는 `@RunWith`를  `@ExtendWith` 를 사용해서 그 기능을 대체하는데

최신 버전의 스프링 부트는 JUnit 5를 사용하기 때문이죠.

또한, `@SpringBootTest`라는 통합 테스트 어노테이션을 통해 `@ExtendWith`를 메타 데이터로 포함하고 있기 때문에 `@ExtendWith` 어노테이션의 선언까지도 생략할 수 있게 되었습니다.

<br/>

이정도면 답변이 되었을까요? 

답변 중 오류를 발견하셨거나 의견이 있으시면 comment  추가해주세요.

감사합니다.

**Comment by ksw6169** [comment]
JUnit 버전업에 따른 변경사항도 기재해주셔서 감사합니다. 
답변하시느라 고생하셨습니다.
