### ISSUE TITLE
(2주차) JUnit4 vs JUnit5

### ISSUE THREAD

**Issue by KOO-YS** [team-tancheon/book-lounge#7]
안녕하세요 @ksw6169님

질문드리겠습니다 🎉
2017년도 JUnit5 정식 버전이 릴리즈되었습니다.

JUnit5 버전이 4 버전의 어떤 단점을 개선하고
어떤 컴포넌트(패키지) 구성으로 이루어져있는지 간략하게 설명 부탁 드립니다

> #### JUnit5 공식 github 코드
> https://github.com/junit-team/junit5/
> <img src="https://blog.jetbrains.com/wp-content/uploads/2020/08/junit5-banner.png" style="max-width:30%;">

**Comment by ksw6169** [comment]
벌써 3년이네요.. (아련) 

열심히 답변을 준비해봤습니다. 아래 사항을 참고해주세요. 

(추가로 궁금하거나, 이해가 되지 않거나, 오류가 있는 부분에 대해서는 코멘트로 남겨주세요.)

<br>

## Q1. JUnit 5가 JUnit 4의 어떤 단점을 개선하였는가?
- JUnit 4의 어노테이션 이름이 보다 직관적으로 변경되었고, 다수의 기능이 추가되었습니다.

<br>

## 1. 라이프 사이클 어노테이션의 변화
이전 버전의 JUnit과 테스트 라이프 사이클은 동일하지만, 라이프 사이클을 지원하는 어노테이션의 이름이 직관적으로 변경되었습니다. 
- JUnit 4 : `@BeforeClass` - `@Before` - `@Test` - `@After` - `@AfterClass`
- JUnit 5 : `@BeforeAll` - `@BeforeEach` - `@Test` - `@AfterEach` - `@AfterAll`

<br>

## 2. 테스트의 이름 지정 가능
JUnit 4에서는 테스트의 이름을 지정할 수 없었습니다. (메소드의 이름이 곧 테스트의 이름) 

하지만, JUnit 5에서는 테스트의 이름을 사용자가 직접 지정할 수 있게 되었습니다. 

메소드나 클래스에 `@DisplayName("...")` 을 사용해주면 되는데, 테스트의 이름으로 이모지 설정까지도 가능합니다.

```java
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("A special test case")
class DisplayNameDemo {

    @Test
    @DisplayName("Custom test name containing spaces")
    void testWithDisplayNameContainingSpaces() {
    }

    @Test
    @DisplayName("╯°□°）╯")
    void testWithDisplayNameContainingSpecialCharacters() {
    }

    @Test
    @DisplayName("😱")
    void testWithDisplayNameContainingEmoji() {
    }
}
```

<br>

## 3. Assertion 메소드 추가
JUnit 4에서 지원하는 Assertion 메소드에 추가로 Java 8의 람다를 활용한 Assertion 메소드가 추가되었습니다. 
(JUnit 5가 최소 JDK 8 버전 이상을 사용해야 사용 가능하니까 추가한 기능이 아닐런지..)

```java
@Test
void standardAssertions() {
	assertEquals(2, calculator.add(1, 1));
	assertEquals(4, calculator.multiply(2, 2),
		"The optional failure message is now the last parameter");
	assertTrue('a' < 'b', () -> "Assertion messages can be lazily evaluated -- "
		+ "to avoid constructing complex messages unnecessarily.");
}

@Test
void groupedAssertions() {
	// In a grouped assertion all assertions are executed, and all
	// failures will be reported together.
	assertAll("person",
		() -> assertEquals("Jane", person.getFirstName()),
		() -> assertEquals("Doe", person.getLastName())
    );
}
```

<br>

## 4. `@Ignore` → `@Disabled`
JUnit 4의 `@Ignore` 는 클래스나, 메소드에서 테스트가 수행되지 않도록 비활성화하는 어노테이션입니다. 이 어노테이션이 JUnit 5에서는 `@Disabled`로 변경되었습니다. `@Disabled` 에는 이 테스트 케이스를 비활성화한 이유에 대해 간단한 설명을 입력할 수 있습니다.

```java
@Test
@Disabled("그냥 하기 싫어~")
void skippedTest() {
    // not executed
}
```

<br>

## 5. 생성자, 메소드에 매개변수 설정 가능
- 테스트의 유연성을 부여하고, 생성자 메소드에 대한 의존성 주입을 위해 JUnit 5에서는 생성자와 메소드에 매개변수를 설정할 수 있습니다. 
- 자세한 사항은 [링크](https://junit.org/junit5/docs/current/user-guide/#writing-tests-dependency-injection)를 참고해주세요.

<br>

## 6. 기타
- 테스트를 병렬로 실행할 수 있습니다. (JUnit 5.3부터 지원하는 실험 기능으로 매개변수, 실행 모드를 설정하면 사용 가능. 자세한 사항은 [링크](https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution) 참고)
- Kotlin을 지원합니다. (Kotlin을 위한 Assertion 메소드도 제공)

<br>

## Q2. JUnit 5는 어떤 컴포넌트(패키지) 구성으로 이루어져 있는가?
JUnit 4는 단일 모듈 구성이었던 것에 비해 JUnit 5는 크게 `JUnit Platform`, `JUnit Jupiter`, `JUnit Vintage` 모듈로 구성되어 있습니다. 아래 설명을 한번 읽어보시고, 이 [링크](https://javacan.tistory.com/entry/JUnit-5-Intro)의 모듈 개요에 나와 있는 모듈 도식도를 한번 살펴보시기 바랍니다.

<br>

**`JUnit Platform`**
- JVM 기반 테스팅 프레임워크를 실행시키기 위한 기반 모듈입니다. (실제 구현체는 다른 모듈에 있음)
- 이 모듈에서는 테스트를 발견하고, 테스트 계획을 생성하는 `TestEngine` 인터페이스를 정의하고 있는데, `TestEngine`의 실제 구현체는 `JUnit Jupiter` 에 `jupiter-engine` 이라는 이름으로 구현되어 있습니다. 

<br>

**`JUnit Jupiter`**
- JUnit 5 기반의 테스트 코드 작성(`jupiter-api`), 테스트 실행(`jupter-engine`)을 위한 모듈입니다.
- 이 모듈을 이용해 JUnit 5 기반의 테스트 코드를 작성하고 실행할 수 있습니다. (`JUnit Platform`에서 정의한 `TestEngine`의 구현체(`jupiter-engine`)가 이 모듈 안에 있음)

<br>

**`JUnit Vintage`**
- JUnit 3, JUnit 4에서 작성한 테스트를 `JUnit Platform`에서 실행시키기 위한 테스트 엔진(`TestEngine`) 인터페이스의 구현체입니다.

<br>

## 참고 자료
- [[JUnit5] Junit4에서 Junit5로](https://sabarada.tistory.com/79)
- [JUnit 5 소개](https://javacan.tistory.com/entry/JUnit-5-Intro)
- [JUnit 5 (2)](https://awayday.github.io/2017-10-29/junit5-02/)
- [JUnit 5 사용자 가이드](https://junit.org/junit5/docs/current/user-guide/#overview)
