### ISSUE TITLE
(3주차) 전략 패턴과 템플릿/콜백 패턴의 차이점

### ISSUE THREAD

**Issue by ksw6169** [team-tancheon/book-lounge#8]
@KOO-YS 님
전략 패턴과 템플릿/콜백 패턴의 차이점에 대해서 설명해주세요. 
가능하다면 이해를 위해 코드도 첨부해주시면 감사하겠습니다.

**Comment by KOO-YS** [comment]
안녕하세요 @ksw6169 님
두 패턴의 특징을 코드👨‍💻  위주로 설명해보았습니다

각 패턴의 특징을 먼저 서술하겠습니다.
<br>
### 전략 패턴
- 클라이언트가 전략 오브젝트를 선택해서 컨텍스트가 활용
- 전략 패턴의 구성
  - **컨택스트** : 변하지 않는 부분
  - **전략** : 필요에 따라 변하는 부분
- 오브젝트를 아예 둘로 분리하고 클래스 레벨에서는 인터페이스를 통해서만 의존
```java
// 클라이언트 -> 컨텍스트 -> 전략
public class Client{
    public void methodOfClient(){		// 클라이언트에서 컨텍스트 메소드를 사용
        // 컨텍스트 생성
        Context context = new Context();

        // 전략 인터페이스 = new 구현 전략(필요에 따라 달라지는 부분)
        Strategy_Interface strategy = new Strategy_Implement();   

        // 컨텍스트가 구현된 전략을 제공받아 사용
        context.contextWithStrategy(strategy);
    }
}


/*   컨텍스트  */
public class Context {
    public void contextWithStrategy(Strategy_Interface st){
        // 컨텍스트 안에서 전략을 수행
    }
}


/*  전략  */
public interface Strategy_Interface {		// 전략 인터페이스
    public void action();
}

public class Strategy_Implement {		// 전략을 클래스로 구현
    @Override
    public void action(){
        // 내맘대로 바꾸는 부분 ~
    }
}
```

### 템플릿/콜백 패턴
- 인터페이스를 상속하는 클래스를 따로 만들지 않고 **익명 내부 클래스**를 활용
- 클라이언트가 템플릿에 콜백을 전달하면 템플릿이 _**참조할 정보**_를 가지고 콜백을 호출
- 템플릿/콜백의 구성
  - **템플릿** : 고정된 틀 안에 (바꿀수 있는 부분-> 콜백 활용)를 넣어서 사용하는 경우
  - **콜백** : 익명 내부 클래스로 만들어지며, _**특정 로직**_을 담은 메소드를 실행하기 위한 오브젝트
- 콜백 메소드에 템플릿 작업 흐름 중 만들어지는 **참조 정보**를 전달받아 만들어지는 특징

```java
public class Client{
    public void methodOfClient(){		
    	Template template = new Template();
        
        // 콜백 함수 -> 익명 메소드로 구현
        Callback temp_Callback = new Callback(){
            @Override
            public int calculate(int A, int B){
            	return (A와 B를 가지고 특정 계산을 한 결과값);
            }
        };
    	
       	template.template_Method(temp_Callback, 다른 정보 ... etc);
    }
}


/*  템플릿  */
public class Template {		// 인터페이스  -> 클래스로 구현 X
    // 템플릿 내부에서 콜백 오브젝트를 호출
    public int template_Method(int Callback callback, T 다른 정보){
        int A = &*%;
        int B = !@#$%;
        int result = callback.calculate(A, B);   
        // -> 템플릿에서 컨텍스트 정보를 전달하고 결과를 받음
    }
}


/*  콜백  */
public interface Callback {		// 인터페이스  -> 클래스로 구현 X
    public int calculate(int A, int B);
}
```
---

두 패턴의 차이점으론
우선 **템플릿/콜백 패턴**의 경우 **템플릿의 흐름 정보가 콜백 함수에 반영되어 작업을 진행한다는 점**이 있습니다.
또한 
`전략 패턴`의 경우 인터페이스의 사용 유무와 싱글톤 유지와 상관없이 DI의 필요성 때문에 런타임 시점에 전략이 생성됩니다.
그와 달리 `템플릿/콜백 패턴`은 템플릿이 콜백을 호출하는 시점에서 전략이 생성됩니다.

---

답변이 잘 되었을까요?
이해가 되지 않는 내용은 코멘트하면 추가 설명드리겠습니다

**Comment by ksw6169** [comment]
안녕하세요. 답변 잘 보았습니다.
궁금한 점이 있습니다.

<br>

1. 템플릿/콜백 패턴의 예시로 보여 주신 코드에서 템플릿이 인터페이스로 설정되어 있는데 인터페이스가 맞는지 궁금합니다.

<br>

2. 설명하신 내용 중 일부 내용이 이해가 되지 않습니다. 제가 아래와 같이 임의로 해석해보았는데 맞는 말인지 궁금합니다.
**_두 패턴의 차이점으론 우선 템플릿/콜백 패턴의 경우 템플릿의 흐름 정보가 콜백 함수에 반영되어 작업을 진행한다는 점이 있습니다._** 
→ 템플릿의 일부 기능(상황에 따라 변하는 코드)이 콜백의 메소드로 분리되어 작업을 진행한다.

<br>

답변주시면 감사하겠습니다.

**Comment by KOO-YS** [comment]
1. 코드에 오류가 있었습니다. 인터페이스가 아닌 클래스로 설정하는게 맞습니다. 수정했습니다. 좋은 지적 감사합니다 👍 
2. 애매한 답변이라 생각은 드나, 위와 같은 답변을 남기게 된 이유를 설명하도록 하겠습니다
> 우선 결론적으로 `전략 패턴`과 `템플릿/콜백 패턴`은 큰 차이를 두고 있는 패턴들이 아닙니다. 많은 구글링을 거친 결과 `템플릿/콜백 패턴`은 **전략 패턴에 콜백 방식으로 확장시킨 형식**이라고 결론을 지었습니다.
>
>(또한, 사실은 템플릿/콜백 패턴이라는 것이 정식 표준 패턴인지 의문점❓이 들었습니다. `토비의 스프링`의 영향력이 끼치는 우리나라 글 이외 해외 자료를 찾아보기 힘들었기 때문입니다..?)
>
>본 책에서는 `템플릿/콜백 패턴`에 대해서는 템플릿의 정보를 콜백 함수에 반영할 때 특화되었다고 생각했기에 `차이점-> 정정 : 강점`에 저 설명을 적었습니다.
>두 패턴을 단정지을 확연한 차이가 없다고 가정하에 **두 패턴의 활용 부분에 초점을 맞춰** 답변하였기 때문에 애매한 답변이 나온 것 같습니다. 이해 부탁드립니다.

추가로 질문있으시다면 코멘트 부탁드립니다. 😄

**Comment by ksw6169** [comment]
@KOO-YS 님
답변주셔서 감사합니다~
