### ISSUE TITLE
(3주차) 스프링의 템플릿/콜백

### ISSUE THREAD

**Issue by ririkat** [team-tancheon/book-lounge#9]
@ksw6169 님

스프링에서 템플릿/콜백 방식을 사용할 때 좋은 점과
스프링에서 제공하는 템플릿/콜백 기술인 JdbcTemplate에 대한 대표적인 예와 간략한 설명 부탁드립니다.
실제 사용 예까지 적어주시면 감사하겠습니다.

**Comment by ksw6169** [comment]
@ririkat 님 안녕하세요.
아래 답변 참고 부탁드립니다. 
추가로 궁금하시거나 이해가 되지 않는 내용은 코멘트로 남겨주세요.

## Q. 스프링에서 템플릿/콜백 방식을 사용할 때 좋은점
`Spring JDBC`에서는 다양한 템플릿과 콜백 인터페이스를 사전 정의한 `JdbcTemplate`을 제공하기 때문에 JDBC를 이용한 DAO 코드에서 템플릿/콜백 패턴을 간편하게 적용할 수 있어 좋습니다.

<br>

참고로 `JdbcTemplate`은 아래와 같은 장점을 가집니다.
- 다양한 템플릿, 콜백 인터페이스가 사전 정의되어 있기 때문에 입맛에 맞게 가져다 사용하면 됩니다.
- 콜백 인터페이스를 직접 구현하지 않더라도 내장 콜백(내부적으로 이미 구현되어 있는 콜백)을 사용하는 메소드를 제공하기 때문에 콜백 인터페이스 구현 없이 더욱 간편하게 사용이 가능합니다.

<br>

## Q. `JdbcTemplate`에 대한 간략한 설명, 대표적인 예, 실제 사용 예시
`JdbcTemplate`은 `Spring JDBC`에서 JDBC 프로그래밍을 간편하게 할 수 있도록 제공하는 JDBC 템플릿을 말합니다. 

<br>

실제 사용 예시는 [링크](https://github.com/ksw6169/toby-of-spring/tree/main/example/src/main/java/com/corgi/example/chapter3/dao/example9)에 첨부된 코드를 참고해주시면 감사하겠습니다.

**Comment by ririkat** [comment]
간략하게 핵심만 잘 설명해주셔서 이해가 쉬웠습니다. close 하겠습니다
